# Generated by Django 5.2.3 on 2026-02-27 22:14

import beeapi.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('url', models.CharField(max_length=200, unique=True)),
                ('token', models.CharField(max_length=200, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Servidores',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeid', models.CharField(default=beeapi.models.retorna_uuid, editable=False, max_length=200, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('label_template', models.TextField(blank=True, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('icone', models.CharField(blank=True, choices=[('bee-router', 'bee-router'), ('bee-switch', 'bee-switch'), ('bee-network-wired', 'bee-network-wired'), ('bee-server', 'bee-server'), ('bee-circle-dot', 'bee-circle-dot'), ('bee-cloud', 'bee-cloud')], default='bee-server', max_length=100, null=True)),
                ('classe', models.CharField(blank=True, choices=[('node', 'node'), ('label', 'label'), ('nota', 'nota'), ('marcador', 'marcador')], default='node', max_length=100, null=True)),
                ('indicador', models.JSONField(blank=True, null=True)),
                ('mapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beeapi.mapa')),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edgeid', models.CharField(default=beeapi.models.retorna_uuid, editable=False, max_length=200, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('label_template', models.TextField(blank=True, null=True)),
                ('indicador', models.JSONField(blank=True, null=True)),
                ('mapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beeapi.mapa')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodeids', to='beeapi.node', to_field='nodeid')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodeidt', to='beeapi.node', to_field='nodeid')),
            ],
        ),
        migrations.AddField(
            model_name='mapa',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beeapi.servidor'),
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(fields=('nome', 'mapa'), name='unique_node_nome_mapa'),
        ),
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.UniqueConstraint(fields=('nome', 'mapa'), name='unique_edge_nome_mapa'),
        ),
    ]
